# Generated by Django 4.1.3 on 2022-11-19 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("demo", "0003_alter_studentinfo_stu_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentinfo",
            name="stu_name",
            field=models.CharField(max_length=30),
        ),
    ]
