# Generated by Django 2.0 on 2022-12-05 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0004_alter_studentinfo_stu_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('user_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=30)),
                ('user_psw', models.CharField(max_length=20)),
                ('user_sex', models.CharField(max_length=10)),
            ],
        ),
    ]
